package bookReviewer.entity.user;

public enum ActivityType {
    BOOK_CREATED,
    RATING_CREATED_WITH_COMMENT,
    RATING_CREATED,
    BOOK_DELETED_BY_ADMIN,
    RATING_DELETED_BY_ADMIN,
    RATING_DELETED_BY_MODERATOR
}
